### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by LukaszFokin** [piotr-e/Stk1160-raspberrypi#5]
hey man... are you ok?

Could you help me to make easycap workt on raspbian?

Im tried it for long days but with no success. 

if you can help me, I'd be grateful.

**Comment by wtgee** [comment]
Hi! I dug into this some back in the day and basically the info I found out is that there are hardware problems with the USB controller on raspberry pi model B. They expect to have this fixed on model C I have heard but can't verify that. 

I'm not totally sure this is true and would still love to get it working on model B but haven't spent the time on it recently because I haven't had the time to work on this project. However, I am actually supposed to begin work on it again within next two weeks so will let you know! Please let me know if you find out anything.

aloha!

**Comment by piotr-e** [comment]
Hi,

In my opinion USB work better and maybe easycap will show correct video, but...

First. You must use old image of Rasbian with kernel 3.2.27.

Next. To compile kernel.

Next. To compile and to install driver for easycap.

Next. To check driver with easycap and to make screenshot of video. ;-)

Next. To make sudo apt-get update and sudo apt-get upgrade. It takes a long time....

Next. To run easycap and to compare screenshot with current video.... ;-)

---

PS. I'm sorry for late answer.

**Comment by piotr-e** [comment]
update...

Some screenshots for kernel 3.10.24 after upgrade from 3.2.27 and mplayer.

<a href='http://wstaw.org/w/2qK4/'><img src='http://wstaw.org/m/2014/01/06/2_3.10.24_jpg_300x300_q85.jpg'></a>

...but sometimes:

<a href='http://wstaw.org/w/2qK5/'><img src='http://wstaw.org/m/2014/01/06/3_3.10.24_jpg_300x300_q85.jpg'></a>

For compare earlier was:

<a href='http://wstaw.org/w/2qK7/'><img src='http://wstaw.org/m/2014/01/06/3_3.2.27_jpg_300x300_q85.jpg'></a>

---

So, for the other software eg. "motion" without X maybe it works better....
